import { createServer } from "node:http";
import { env } from "./lib/env.js";
import { logger } from "./lib/logger.js";
import { createRealtimeServer } from "./ws/server.js";
import { handleSnapshotRequest } from "./routes/snapshot.js";
import { connections } from "./ws/broadcast.js";
const httpServer=createServer((req,res)=>{ if(req.method==="GET"&&req.url==="/health"){res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify({status:"ok",connections:connections.size}));return;} if(req.method==="GET"&&req.url==="/snapshot"){handleSnapshotRequest(req,res);return;} res.writeHead(404,{"Content-Type":"application/json"});res.end(JSON.stringify({error:"Not found"})); });
createRealtimeServer(httpServer);
process.on("SIGINT",()=>httpServer.close(()=>process.exit(0))); process.on("SIGTERM",()=>httpServer.close(()=>process.exit(0)));
httpServer.listen(env.REALTIME_PORT,env.REALTIME_HOST,()=>logger.info(`VANTA realtime listening on ${env.REALTIME_HOST}:${env.REALTIME_PORT}`));
