export const PROTOCOL_VERSION = 1;

export const MESSAGE_TYPES = {
  CONNECT: "CONNECT",
  AUTH: "AUTH",
  CLIENT_HELLO: "CLIENT_HELLO",
  PILOT_CONNECT: "PILOT_CONNECT",
  PILOT_UPDATE: "PILOT_UPDATE",
  PILOT_DISCONNECT: "PILOT_DISCONNECT",
  FLIGHT_PLAN: "FLIGHT_PLAN",
  ATC_CONNECT: "ATC_CONNECT",
  ATC_DISCONNECT: "ATC_DISCONNECT",
  FREQUENCY_UPDATE: "FREQUENCY_UPDATE",
  PTT_START: "PTT_START",
  PTT_STOP: "PTT_STOP",
  VOICE_METADATA: "VOICE_METADATA",
  AIRCRAFT_UPDATE: "AIRCRAFT_UPDATE",
  PING: "PING",
  PONG: "PONG"
} as const;

export const DEFAULT_RADIO_RANGE_NM = 150;
export const MAX_TELEMETRY_RATE_HZ = 10;
